### ISSUE TITLE
Failover leader election timeout with a minute

### ISSUE THREAD

**Issue by hebelala** [vipshop/Saturn#102] opened 2017-03-07 11:01 UTC
Failover leader election timeout with a minute, log warn

**Comment by duffqiu** [comment] 2017-03-07 14:55
what will happen after one minute？

**Comment by IvyLee-cn** [comment] 2017-03-10 06:55
It caused by a bug in curator-framework which has been fixed in 2.8.0.
https://issues.apache.org/jira/browse/CURATOR-168

**Closed** 2017-03-20 09:23 UTC
Labels: done, enhancement
